theme: jekyll-theme-minimal
title: Cartel Activista
description: ##La yuxtaposición del mundo digital sobre el físico.
description: Esta galería digital dispone diferentes experiencias en realidad aumentada para acompañar la protesta.
